baseURL: 'http://example.org/'
languageCode: ko-kr
title: 'Ubuntu Korea Community'
theme: "ubuntukr"
buildFuture: true
params:
  contact: contact@ubuntu-kr.org

defaultContentLanguage: ko
languages:
  ko:
    languageName: 한국어
    title: 우분투 한국 커뮤니티
    weight: 1
    params:
      description: >-
        우분투 한국 커뮤니티는 Ubuntu Community Council에서 인증한 공식 한국 커뮤니티이며,
        우분투(Ubuntu)를 사용하는 사람, 개발하는 사람, 우분투 프로젝트에 기여하는 사람, 우분투에 관심이 있는 모두를 위한 커뮤니티 입니다.
    menu:
      main:
      - identifier: try
        name: 우분투 사용해보기
        url: try
        weight: 1
      - identifier: docs
        name: 문서
        url: docs
        weight: 2
      - identifier: wiki-ko
        parent: docs
        name: 위키(한국어)
        url: https://wiki.ubuntu-kr.org
        weight: 20
      - identifier: tutorials-ko
        parent: docs
        name: 튜토리얼(한국어)
        url: https://ubuntu-kr.github.io/workshops/
        weight: 21
      - identifier: docs-en
        parent: docs
        name: 문서(영문)
        url: https://docs.ubuntu.com
        weight: 22
      - identifier: tutorials-en
        parent: docs
        name: 튜토리얼(영문)
        url: https://ubuntu.com/tutorials
        weight: 23
      - identifier: wiki-en
        parent: docs
        name: 위키(영문)
        url: https://wiki.ubuntu.com
        weight: 24
      - identifier: community
        name: 커뮤니티
        url: community
        weight: 3
      - identifier: forum
        parent: community
        name: 포럼
        url: https://forum.ubuntu-kr.org
        weight: 3
      - identifier: fb-group
        parent: community
        name: 페이스북 그룹
        url: https://fb.com/groups/ubuntu.ko
        weight: 3
      - identifier: lists
        parent: community
        name: 메일링 리스트
        url: https://lists.ubuntu.com/archives/ubuntu-ko/
        weight: 3
      - identifier: chat
        parent: community
        name: 채팅(Slack, IRC)
        url: chat
        weight: 3
      - identifier: partandcontrib
        name: 참여 및 기여하기
        url: partandcontrib
        weight: 4
      - identifier: events
        parent: partandcontrib
        name: 행사 참여하기
        url: events
        weight: 4
      - identifier: study_projects
        parent: partandcontrib
        name: 스터디/프로젝트
        url: projects
        weight: 4
      - identifier: translate
        parent: partandcontrib
        name: 우분투 번역하기
        url: translate
        weight: 4
      - identifier: follow
        name: 소식 받기
        weight: 5
      - identifier: blog
        parent: follow
        name: 블로그
        url: https://blog.ubuntu-kr.org
        weight: 4
      - identifier: facebook
        parent: follow
        name: 페이스북
        url: https://fb.com/ubuntukorea
        weight: 4
      - identifier: twitter
        parent: follow
        name: 트위터
        url: https://twitter.com/UbuntuKrOrg
        weight: 4
      - identifier: youtube
        parent: follow
        name: YouTube
        url: https://www.youtube.com/user/UbuntuKorea
        weight: 4
  en:
    languageName: English
    title: Ubuntu Korea Community
    weight: 2
    params:
      description: >-
        Ubuntu Korea Community is a Ubuntu LoCo(Local Community) in South Korea verified by Ubuntu Community Council,
        It is a place for everyone who intrested in using, developing with ubuntu, or contributing to ubuntu projects.
    menu:
      main:
      - identifier: try
        name: Try Ubuntu
        url: try
        weight: 1
      - identifier: docs
        name: Documentations
        url: docs
        weight: 2
      - identifier: community
        name: Community
        url: community
        weight: 3
      - identifier: partandcontrib
        name: Participate & Contribute
        url: partandcontrib
        weight: 4